"""
添加元素定位信息表

Revision ID: 20240328_add_element_locator
Revises: 
Create Date: 2024-03-28 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20240328_add_element_locator'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('element_locators',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('step_id', sa.Integer(), nullable=False),
        sa.Column('element_description', sa.String(length=255), nullable=True),
        sa.Column('element_type', sa.String(length=50), nullable=True),
        sa.Column('css_selector', sa.String(length=500), nullable=True),
        sa.Column('xpath', sa.String(length=500), nullable=True),
        sa.Column('element_id', sa.String(length=100), nullable=True),
        sa.Column('element_name', sa.String(length=100), nullable=True),
        sa.Column('element_class', sa.String(length=255), nullable=True),
        sa.Column('element_text', sa.String(length=500), nullable=True),
        sa.Column('ai_coordinate', sa.JSON(), nullable=True),
        sa.Column('ai_confidence', sa.Float(), nullable=True),
        sa.Column('success_count', sa.Integer(), nullable=True),
        sa.Column('fail_count', sa.Integer(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('source', sa.String(length=20), nullable=True),
        sa.Column('version', sa.Integer(), nullable=True, server_default='0'),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_element_locators_id'), 'element_locators', ['id'], unique=False)
    op.create_index(op.f('ix_element_locators_step_id'), 'element_locators', ['step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_element_locators_step_id'), table_name='element_locators')
    op.drop_index(op.f('ix_element_locators_id'), table_name='element_locators')
    op.drop_table('element_locators')
    # ### end Alembic commands ###
